# configuration.yml file
data_sources snowflake:
  type: snowflake
  host: soda-demo
  account: yl32188.central-india.azure.snowflakecomputing.com
  username: mukesh789
  password: Mukesh@1234
  database: DBMS
  schema: SCOTT
   warehouse: compute_wh
# Refer to https://go.soda.io/api-keys
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: 5d407976-7091-4901-9fa5-80f947c7b18b
  api_key_secret: r7Etzjhwqi_jc6VWAPkB9RX2b8waBHaQOz9ponJX4Ul91uzxlhSERw
  
